In [222]:
import pandas as pd

In [223]:
df = pd.read_csv(r"C:\Users\ibrah\OneDrive\Desktop\Workshop\Pandas_Keith\pokemon_data.csv")
df.head(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

To see the columns

In [224]:
df.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

### Reading the Headers

In [225]:
# Reading headers
print(df.columns)

#  reading each column
print(df['Name'][:5])

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')
0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
Name: Name, dtype: object

In [226]:
print(df.Attack[:5])

0     49
1     62
2     82
3    100
4     52
Name: Attack, dtype: int64

In [346]:
df[2:5]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total,Status,count
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,999,False,526,Great,1
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,999,False,626,Great,1
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,310,Good,1

In [227]:
#  reading each row
df.iloc[1:9]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False

In [228]:
#  iloc is used to print a specific row or all rows iloc[rows,columns]
print(df.iloc[2,1])

print(df.iloc[6,:])

Venusaur
#                     6
Name          Charizard
Type 1             Fire
Type 2           Flying
HP                   78
Attack               84
Defense              78
Sp. Atk             109
Sp. Def              85
Speed               100
Generation            1
Legendary         False
Name: 6, dtype: object

to itterate rows

In [229]:
for index,rows in df.iterrows():
    print(index,rows['Name'])

0 Bulbasaur
1 Ivysaur
2 Venusaur
3 VenusaurMega Venusaur
4 Charmander
5 Charmeleon
6 Charizard
7 CharizardMega Charizard X
8 CharizardMega Charizard Y
9 Squirtle
10 Wartortle
11 Blastoise
12 BlastoiseMega Blastoise
13 Caterpie
14 Metapod
15 Butterfree
16 Weedle
17 Kakuna
18 Beedrill
19 BeedrillMega Beedrill
20 Pidgey
21 Pidgeotto
22 Pidgeot
23 PidgeotMega Pidgeot
24 Rattata
25 Raticate
26 Spearow
27 Fearow
28 Ekans
29 Arbok
30 Pikachu
31 Raichu
32 Sandshrew
33 Sandslash
34 Nidoran (Female)
35 Nidorina
36 Nidoqueen
37 Nidoran (Male)
38 Nidorino
39 Nidoking
40 Clefairy
41 Clefable
42 Vulpix
43 Ninetales
44 Jigglypuff
45 Wigglytuff
46 Zubat
47 Golbat
48 Oddish
49 Gloom
50 Vileplume
51 Paras
52 Parasect
53 Venonat
54 Venomoth
55 Diglett
56 Dugtrio
57 Meowth
58 Persian
59 Psyduck
60 Golduck
61 Mankey
62 Primeape
63 Growlithe
64 Arcanine
65 Poliwag
66 Poliwhirl
67 Poliwrath
68 Abra
69 Kadabra
70 Alakazam
71 AlakazamMega Alakazam
72 Machop
73 Machoke
74 Machamp
75 Bellsprout
76 Weepinbell
77 Victreebel
78 Tentacool
79 Tentacruel
80 Geodude
81 Graveler
82 Golem
83 Ponyta
84 Rapidash
85 Slowpoke
86 Slowbro
87 SlowbroMega Slowbro
88 Magnemite
89 Magneton
90 Farfetch'd
91 Doduo
92 Dodrio
93 Seel
94 Dewgong
95 Grimer
96 Muk
97 Shellder
98 Cloyster
99 Gastly
100 Haunter
101 Gengar
102 GengarMega Gengar
103 Onix
104 Drowzee
105 Hypno
106 Krabby
107 Kingler
108 Voltorb
109 Electrode
110 Exeggcute
111 Exeggutor
112 Cubone
113 Marowak
114 Hitmonlee
115 Hitmonchan
116 Lickitung
117 Koffing
118 Weezing
119 Rhyhorn
120 Rhydon
121 Chansey
122 Tangela
123 Kangaskhan
124 KangaskhanMega Kangaskhan
125 Horsea
126 Seadra
127 Goldeen
128 Seaking
129 Staryu
130 Starmie
131 Mr. Mime
132 Scyther
133 Jynx
134 Electabuzz
135 Magmar
136 Pinsir
137 PinsirMega Pinsir
138 Tauros
139 Magikarp
140 Gyarados
141 GyaradosMega Gyarados
142 Lapras
143 Ditto
144 Eevee
145 Vaporeon
146 Jolteon
147 Flareon
148 Porygon
149 Omanyte
150 Omastar
151 Kabuto
152 Kabutops
153 Aerodactyl
154 AerodactylMega Aerodactyl
155 Snorlax
156 Articuno
157 Zapdos
158 Moltres
159 Dratini
160 Dragonair
161 Dragonite
162 Mewtwo
163 MewtwoMega Mewtwo X
164 MewtwoMega Mewtwo Y
165 Mew
166 Chikorita
167 Bayleef
168 Meganium
169 Cyndaquil
170 Quilava
171 Typhlosion
172 Totodile
173 Croconaw
174 Feraligatr
175 Sentret
176 Furret
177 Hoothoot
178 Noctowl
179 Ledyba
180 Ledian
181 Spinarak
182 Ariados
183 Crobat
184 Chinchou
185 Lanturn
186 Pichu
187 Cleffa
188 Igglybuff
189 Togepi
190 Togetic
191 Natu
192 Xatu
193 Mareep
194 Flaaffy
195 Ampharos
196 AmpharosMega Ampharos
197 Bellossom
198 Marill
199 Azumarill
200 Sudowoodo
201 Politoed
202 Hoppip
203 Skiploom
204 Jumpluff
205 Aipom
206 Sunkern
207 Sunflora
208 Yanma
209 Wooper
210 Quagsire
211 Espeon
212 Umbreon
213 Murkrow
214 Slowking
215 Misdreavus
216 Unown
217 Wobbuffet
218 Girafarig
219 Pineco
220 Forretress
221 Dunsparce
222 Gligar
223 Steelix
224 SteelixMega Steelix
225 Snubbull
226 Granbull
227 Qwilfish
228 Scizor
229 ScizorMega Scizor
230 Shuckle
231 Heracross
232 HeracrossMega Heracross
233 Sneasel
234 Teddiursa
235 Ursaring
236 Slugma
237 Magcargo
238 Swinub
239 Piloswine
240 Corsola
241 Remoraid
242 Octillery
243 Delibird
244 Mantine
245 Skarmory
246 Houndour
247 Houndoom
248 HoundoomMega Houndoom
249 Kingdra
250 Phanpy
251 Donphan
252 Porygon2
253 Stantler
254 Smeargle
255 Tyrogue
256 Hitmontop
257 Smoochum
258 Elekid
259 Magby
260 Miltank
261 Blissey
262 Raikou
263 Entei
264 Suicune
265 Larvitar
266 Pupitar
267 Tyranitar
268 TyranitarMega Tyranitar
269 Lugia
270 Ho-oh
271 Celebi
272 Treecko
273 Grovyle
274 Sceptile
275 SceptileMega Sceptile
276 Torchic
277 Combusken
278 Blaziken
279 BlazikenMega Blaziken
280 Mudkip
281 Marshtomp
282 Swampert
283 SwampertMega Swampert
284 Poochyena
285 Mightyena
286 Zigzagoon
287 Linoone
288 Wurmple
289 Silcoon
290 Beautifly
291 Cascoon
292 Dustox
293 Lotad
294 Lombre
295 Ludicolo
296 Seedot
297 Nuzleaf
298 Shiftry
299 Taillow
300 Swellow
301 Wingull
302 Pelipper
303 Ralts
304 Kirlia
305 Gardevoir
306 GardevoirMega Gardevoir
307 Surskit
308 Masquerain
309 Shroomish
310 Breloom
311 Slakoth
312 Vigoroth
313 Slaking
314 Nincada
315 Ninjask
316 Shedinja
317 Whismur
318 Loudred
319 Exploud
320 Makuhita
321 Hariyama
322 Azurill
323 Nosepass
324 Skitty
325 Delcatty
326 Sableye
327 SableyeMega Sableye
328 Mawile
329 MawileMega Mawile
330 Aron
331 Lairon
332 Aggron
333 AggronMega Aggron
334 Meditite
335 Medicham
336 MedichamMega Medicham
337 Electrike
338 Manectric
339 ManectricMega Manectric
340 Plusle
341 Minun
342 Volbeat
343 Illumise
344 Roselia
345 Gulpin
346 Swalot
347 Carvanha
348 Sharpedo
349 SharpedoMega Sharpedo
350 Wailmer
351 Wailord
352 Numel
353 Camerupt
354 CameruptMega Camerupt
355 Torkoal
356 Spoink
357 Grumpig
358 Spinda
359 Trapinch
360 Vibrava
361 Flygon
362 Cacnea
363 Cacturne
364 Swablu
365 Altaria
366 AltariaMega Altaria
367 Zangoose
368 Seviper
369 Lunatone
370 Solrock
371 Barboach
372 Whiscash
373 Corphish
374 Crawdaunt
375 Baltoy
376 Claydol
377 Lileep
378 Cradily
379 Anorith
380 Armaldo
381 Feebas
382 Milotic
383 Castform
384 Kecleon
385 Shuppet
386 Banette
387 BanetteMega Banette
388 Duskull
389 Dusclops
390 Tropius
391 Chimecho
392 Absol
393 AbsolMega Absol
394 Wynaut
395 Snorunt
396 Glalie
397 GlalieMega Glalie
398 Spheal
399 Sealeo
400 Walrein
401 Clamperl
402 Huntail
403 Gorebyss
404 Relicanth
405 Luvdisc
406 Bagon
407 Shelgon
408 Salamence
409 SalamenceMega Salamence
410 Beldum
411 Metang
412 Metagross
413 MetagrossMega Metagross
414 Regirock
415 Regice
416 Registeel
417 Latias
418 LatiasMega Latias
419 Latios
420 LatiosMega Latios
421 Kyogre
422 KyogrePrimal Kyogre
423 Groudon
424 GroudonPrimal Groudon
425 Rayquaza
426 RayquazaMega Rayquaza
427 Jirachi
428 DeoxysNormal Forme
429 DeoxysAttack Forme
430 DeoxysDefense Forme
431 DeoxysSpeed Forme
432 Turtwig
433 Grotle
434 Torterra
435 Chimchar
436 Monferno
437 Infernape
438 Piplup
439 Prinplup
440 Empoleon
441 Starly
442 Staravia
443 Staraptor
444 Bidoof
445 Bibarel
446 Kricketot
447 Kricketune
448 Shinx
449 Luxio
450 Luxray
451 Budew
452 Roserade
453 Cranidos
454 Rampardos
455 Shieldon
456 Bastiodon
457 Burmy
458 WormadamPlant Cloak
459 WormadamSandy Cloak
460 WormadamTrash Cloak
461 Mothim
462 Combee
463 Vespiquen
464 Pachirisu
465 Buizel
466 Floatzel
467 Cherubi
468 Cherrim
469 Shellos
470 Gastrodon
471 Ambipom
472 Drifloon
473 Drifblim
474 Buneary
475 Lopunny
476 LopunnyMega Lopunny
477 Mismagius
478 Honchkrow
479 Glameow
480 Purugly
481 Chingling
482 Stunky
483 Skuntank
484 Bronzor
485 Bronzong
486 Bonsly
487 Mime Jr.
488 Happiny
489 Chatot
490 Spiritomb
491 Gible
492 Gabite
493 Garchomp
494 GarchompMega Garchomp
495 Munchlax
496 Riolu
497 Lucario
498 LucarioMega Lucario
499 Hippopotas
500 Hippowdon
501 Skorupi
502 Drapion
503 Croagunk
504 Toxicroak
505 Carnivine
506 Finneon
507 Lumineon
508 Mantyke
509 Snover
510 Abomasnow
511 AbomasnowMega Abomasnow
512 Weavile
513 Magnezone
514 Lickilicky
515 Rhyperior
516 Tangrowth
517 Electivire
518 Magmortar
519 Togekiss
520 Yanmega
521 Leafeon
522 Glaceon
523 Gliscor
524 Mamoswine
525 Porygon-Z
526 Gallade
527 GalladeMega Gallade
528 Probopass
529 Dusknoir
530 Froslass
531 Rotom
532 RotomHeat Rotom
533 RotomWash Rotom
534 RotomFrost Rotom
535 RotomFan Rotom
536 RotomMow Rotom
537 Uxie
538 Mesprit
539 Azelf
540 Dialga
541 Palkia
542 Heatran
543 Regigigas
544 GiratinaAltered Forme
545 GiratinaOrigin Forme
546 Cresselia
547 Phione
548 Manaphy
549 Darkrai
550 ShayminLand Forme
551 ShayminSky Forme
552 Arceus
553 Victini
554 Snivy
555 Servine
556 Serperior
557 Tepig
558 Pignite
559 Emboar
560 Oshawott
561 Dewott
562 Samurott
563 Patrat
564 Watchog
565 Lillipup
566 Herdier
567 Stoutland
568 Purrloin
569 Liepard
570 Pansage
571 Simisage
572 Pansear
573 Simisear
574 Panpour
575 Simipour
576 Munna
577 Musharna
578 Pidove
579 Tranquill
580 Unfezant
581 Blitzle
582 Zebstrika
583 Roggenrola
584 Boldore
585 Gigalith
586 Woobat
587 Swoobat
588 Drilbur
589 Excadrill
590 Audino
591 AudinoMega Audino
592 Timburr
593 Gurdurr
594 Conkeldurr
595 Tympole
596 Palpitoad
597 Seismitoad
598 Throh
599 Sawk
600 Sewaddle
601 Swadloon
602 Leavanny
603 Venipede
604 Whirlipede
605 Scolipede
606 Cottonee
607 Whimsicott
608 Petilil
609 Lilligant
610 Basculin
611 Sandile
612 Krokorok
613 Krookodile
614 Darumaka
615 DarmanitanStandard Mode
616 DarmanitanZen Mode
617 Maractus
618 Dwebble
619 Crustle
620 Scraggy
621 Scrafty
622 Sigilyph
623 Yamask
624 Cofagrigus
625 Tirtouga
626 Carracosta
627 Archen
628 Archeops
629 Trubbish
630 Garbodor
631 Zorua
632 Zoroark
633 Minccino
634 Cinccino
635 Gothita
636 Gothorita
637 Gothitelle
638 Solosis
639 Duosion
640 Reuniclus
641 Ducklett
642 Swanna
643 Vanillite
644 Vanillish
645 Vanilluxe
646 Deerling
647 Sawsbuck
648 Emolga
649 Karrablast
650 Escavalier
651 Foongus
652 Amoonguss
653 Frillish
654 Jellicent
655 Alomomola
656 Joltik
657 Galvantula
658 Ferroseed
659 Ferrothorn
660 Klink
661 Klang
662 Klinklang
663 Tynamo
664 Eelektrik
665 Eelektross
666 Elgyem
667 Beheeyem
668 Litwick
669 Lampent
670 Chandelure
671 Axew
672 Fraxure
673 Haxorus
674 Cubchoo
675 Beartic
676 Cryogonal
677 Shelmet
678 Accelgor
679 Stunfisk
680 Mienfoo
681 Mienshao
682 Druddigon
683 Golett
684 Golurk
685 Pawniard
686 Bisharp
687 Bouffalant
688 Rufflet
689 Braviary
690 Vullaby
691 Mandibuzz
692 Heatmor
693 Durant
694 Deino
695 Zweilous
696 Hydreigon
697 Larvesta
698 Volcarona
699 Cobalion
700 Terrakion
701 Virizion
702 TornadusIncarnate Forme
703 TornadusTherian Forme
704 ThundurusIncarnate Forme
705 ThundurusTherian Forme
706 Reshiram
707 Zekrom
708 LandorusIncarnate Forme
709 LandorusTherian Forme
710 Kyurem
711 KyuremBlack Kyurem
712 KyuremWhite Kyurem
713 KeldeoOrdinary Forme
714 KeldeoResolute Forme
715 MeloettaAria Forme
716 MeloettaPirouette Forme
717 Genesect
718 Chespin
719 Quilladin
720 Chesnaught
721 Fennekin
722 Braixen
723 Delphox
724 Froakie
725 Frogadier
726 Greninja
727 Bunnelby
728 Diggersby
729 Fletchling
730 Fletchinder
731 Talonflame
732 Scatterbug
733 Spewpa
734 Vivillon
735 Litleo
736 Pyroar
737 Flabébé
738 Floette
739 Florges
740 Skiddo
741 Gogoat
742 Pancham
743 Pangoro
744 Furfrou
745 Espurr
746 MeowsticMale
747 MeowsticFemale
748 Honedge
749 Doublade
750 AegislashBlade Forme
751 AegislashShield Forme
752 Spritzee
753 Aromatisse
754 Swirlix
755 Slurpuff
756 Inkay
757 Malamar
758 Binacle
759 Barbaracle
760 Skrelp
761 Dragalge
762 Clauncher
763 Clawitzer
764 Helioptile
765 Heliolisk
766 Tyrunt
767 Tyrantrum
768 Amaura
769 Aurorus
770 Sylveon
771 Hawlucha
772 Dedenne
773 Carbink
774 Goomy
775 Sliggoo
776 Goodra
777 Klefki
778 Phantump
779 Trevenant
780 PumpkabooAverage Size
781 PumpkabooSmall Size
782 PumpkabooLarge Size
783 PumpkabooSuper Size
784 GourgeistAverage Size
785 GourgeistSmall Size
786 GourgeistLarge Size
787 GourgeistSuper Size
788 Bergmite
789 Avalugg
790 Noibat
791 Noivern
792 Xerneas
793 Yveltal
794 Zygarde50% Forme
795 Diancie
796 DiancieMega Diancie
797 HoopaHoopa Confined
798 HoopaHoopa Unbound
799 Volcanion

For reading only specific data types

In [230]:
df.loc[df['Type 1'] == "Fire"].head(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False

In [231]:
df.loc[df.HP == 39].head(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
169,155,Cyndaquil,Fire,NaN,39,52,43,60,50,65,2,False

In [232]:
df.loc[df['Type 2'] == 'Flying'].head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False
15,12,Butterfree,Bug,Flying,60,45,50,90,80,70,1,False
20,16,Pidgey,Normal,Flying,40,45,40,35,35,56,1,False
21,17,Pidgeotto,Normal,Flying,63,60,55,50,50,71,1,False

In [233]:
df[df['Type 1'] == 'Bug'].sum

<bound method DataFrame.sum of        #        Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  \
13    10    Caterpie    Bug     NaN  45      30       35       20       20
14    11     Metapod    Bug     NaN  50      20       55       25       25
15    12  Butterfree    Bug  Flying  60      45       50       90       80
16    13      Weedle    Bug  Poison  40      35       30       20       20
17    14      Kakuna    Bug  Poison  45      25       50       25       25
..   ...         ...    ...     ...  ..     ...      ...      ...      ...
698  637   Volcarona    Bug    Fire  85      60       65      135      105
717  649    Genesect    Bug   Steel  71     120       95      120       95
732  664  Scatterbug    Bug     NaN  38      35       40       27       25
733  665      Spewpa    Bug     NaN  45      22       60       27       30
734  666    Vivillon    Bug  Flying  80      52       50       90       50

     Speed  Generation  Legendary
13      45           1      False
14      30           1      False
15      70           1      False
16      50           1      False
17      35           1      False
..     ...         ...        ...
698    100           5      False
717     99           5      False
732     35           6      False
733     29           6      False
734     89           6      False

[69 rows x 12 columns]>

 Describe

In [234]:
df.describe()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

Sorting

In [235]:
df.sort_values('Name',ascending = False).head(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False

In [236]:
df.sort_values(['Type 1','HP'],ascending = True).tail(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
142,131,Lapras,Water,Ice,130,85,80,85,95,60,1,False
145,134,Vaporeon,Water,NaN,130,65,60,110,95,65,1,False
350,320,Wailmer,Water,NaN,130,70,35,70,35,60,3,False
655,594,Alomomola,Water,NaN,165,75,80,40,45,65,5,False
351,321,Wailord,Water,NaN,170,90,45,90,45,60,3,False

### Making Changes to dataset

In [237]:
df['Total'] = df['HP'] + df['Attack']

df.head(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,94
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,122
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,162
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,180
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,91

Droping a Column

In [238]:
df = df.drop(columns = ['Total'])

In [239]:
df.head(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [240]:
df['Total'] = df.iloc[:,4:11].sum(axis = 1)
df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,319
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,406
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,526
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,626
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,310

### Filtering Data

Reset the Index

In [241]:
fdf = df.loc[(df["Type 1"] == "Grass") & (df["Type 2"] == "Poison") & (df['HP'] >= 40)]
fdf.reset_index(inplace = True)
fdf

,index,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,319
1,1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,406
2,2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,526
3,3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,626
4,48,43,Oddish,Grass,Poison,45,50,55,75,65,30,1,False,321
5,49,44,Gloom,Grass,Poison,60,65,70,85,75,40,1,False,396
6,50,45,Vileplume,Grass,Poison,75,80,85,110,90,50,1,False,491
7,75,69,Bellsprout,Grass,Poison,50,75,35,70,30,40,1,False,301
8,76,70,Weepinbell,Grass,Poison,65,90,50,85,45,55,1,False,391
9,77,71,Victreebel,Grass,Poison,80,105,65,100,70,70,1,False,491
10,344,315,Roselia,Grass,Poison,50,60,45,100,80,65,3,False,403
11,451,406,Budew,Grass,Poison,40,30,35,50,70,55,4,False,284
12,452,407,Roserade,Grass,Poison,60,70,65,125,105,90,4,False,519
13,651,590,Foongus,Grass,Poison,69,55,45,55,55,15,5,False,299
14,652,591,Amoonguss,Grass,Poison,114,85,70,85,80,30,5,False,469

### To Update the CSV

In [242]:
fdf.to_csv("Filterxxx.csv")

To Check if any row contains any typw of word

In [243]:
df.loc[df['Name'].str.contains("gus")]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
624,563,Cofagrigus,Ghost,NaN,58,50,145,95,105,30,5,False,488
651,590,Foongus,Grass,Poison,69,55,45,55,55,15,5,False,299
652,591,Amoonguss,Grass,Poison,114,85,70,85,80,30,5,False,469

In [244]:
df.loc[df['Name'].str.contains('pi')].head(5)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           800 non-null    int64
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      414 non-null    object
 4   HP          800 non-null    int64
 5   Attack      800 non-null    int64
 6   Defense     800 non-null    int64
 7   Sp. Atk     800 non-null    int64
 8   Sp. Def     800 non-null    int64
 9   Speed       800 non-null    int64
 10  Generation  800 non-null    int64
 11  Legendary   800 non-null    bool
 12  Total       800 non-null    int64
dtypes: bool(1), int64(9), object(3)
memory usage: 75.9+ KB

In [245]:
df.dropna()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,319
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,406
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,526
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,626
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False,535
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,606
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,706
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,606
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,686
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,606

In [347]:
df.loc[df['Total'] > 500 , ['Generation']] = 999
df.drop(columns=['Status'])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total,count
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,319,1
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,406,1
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,999,False,526,1
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,999,False,626,1
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,310,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,999,True,606,1
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,999,True,706,1
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,999,True,606,1
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,999,True,686,1
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,999,True,606,1

In [250]:
df.loc[df['Total'] > 500 ,['Status']] = "Great"
df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total,Status
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,319,NaN
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,406,NaN
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,999,False,526,Great
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,999,False,626,Great
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,310,NaN

In [329]:
df['Status'].fillna('Good',inplace = True)
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total,Status
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,319,Good
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,406,Good
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,999,False,526,Great
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,999,False,626,Great
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,310,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,999,True,606,Great
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,999,True,706,Great
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,999,True,606,Great
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,999,True,686,Great
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,999,True,606,Great

In [345]:
df.reset_index().drop(columns = ['#'])
df['count'] = 1
dff = df.groupby(['Type 1']).count()['count']
dff

Type 1
Bug          69
Dark         31
Dragon       32
Electric     44
Fairy        17
Fighting     27
Fire         52
Flying        4
Ghost        32
Grass        70
Ground       32
Ice          24
Normal       98
Poison       28
Psychic      57
Rock         44
Steel        27
Water       112
Name: count, dtype: int64

### Aggerate Statistics (Group By)

In [314]:
g = df.groupby('Type 1')
print(g)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x000001AB14D80290>

In [315]:
tt = df['Type 1']
for tt,typ1 in g:
    print(tt)
    print(typ1.reset_index())

Bug
    index    #        Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0      13   10    Caterpie    Bug     NaN  45      30       35       20
1      14   11     Metapod    Bug     NaN  50      20       55       25
2      15   12  Butterfree    Bug  Flying  60      45       50       90
3      16   13      Weedle    Bug  Poison  40      35       30       20
4      17   14      Kakuna    Bug  Poison  45      25       50       25
..    ...  ...         ...    ...     ...  ..     ...      ...      ...
64    698  637   Volcarona    Bug    Fire  85      60       65      135
65    717  649    Genesect    Bug   Steel  71     120       95      120
66    732  664  Scatterbug    Bug     NaN  38      35       40       27
67    733  665      Spewpa    Bug     NaN  45      22       60       27
68    734  666    Vivillon    Bug  Flying  80      52       50       90

    Sp. Def  Speed  Generation  Legendary  Total Status
0        20     45           1      False    196   Good
1        25     30           1      False    206   Good
2        80     70           1      False    396   Good
3        20     50           1      False    196   Good
4        25     35           1      False    206   Good
..      ...    ...         ...        ...    ...    ...
64      105    100         999      False    555  Great
65       95     99         999      False    605  Great
66       25     35           6      False    206   Good
67       30     29           6      False    219   Good
68       50     89           6      False    417   Good

[69 rows x 15 columns]
Dark
    index    #                   Name Type 1    Type 2   HP  Attack  Defense  \
0     212  197                Umbreon   Dark       NaN   95      65      110
1     213  198                Murkrow   Dark    Flying   60      85       42
2     233  215                Sneasel   Dark       Ice   55      95       55
3     246  228               Houndour   Dark      Fire   45      60       30
4     247  229               Houndoom   Dark      Fire   75      90       50
5     248  229  HoundoomMega Houndoom   Dark      Fire   75      90       90
6     284  261              Poochyena   Dark       NaN   35      55       35
7     285  262              Mightyena   Dark       NaN   70      90       70
8     326  302                Sableye   Dark     Ghost   50      75       75
9     327  302    SableyeMega Sableye   Dark     Ghost   50      85      125
10    392  359                  Absol   Dark       NaN   65     130       60
11    393  359        AbsolMega Absol   Dark       NaN   65     150       60
12    478  430              Honchkrow   Dark    Flying  100     125       52
13    512  461                Weavile   Dark       Ice   70     120       65
14    549  491                Darkrai   Dark       NaN   70      90       90
15    568  509               Purrloin   Dark       NaN   41      50       37
16    569  510                Liepard   Dark       NaN   64      88       50
17    620  559                Scraggy   Dark  Fighting   50      75       70
18    621  560                Scrafty   Dark  Fighting   65      90      115
19    631  570                  Zorua   Dark       NaN   40      65       40
20    632  571                Zoroark   Dark       NaN   60     105       60
21    685  624               Pawniard   Dark     Steel   45      85       70
22    686  625                Bisharp   Dark     Steel   65     125      100
23    690  629                Vullaby   Dark    Flying   70      55       75
24    691  630              Mandibuzz   Dark    Flying  110      65      105
25    694  633                  Deino   Dark    Dragon   52      65       50
26    695  634               Zweilous   Dark    Dragon   72      85       70
27    696  635              Hydreigon   Dark    Dragon   92     105       90
28    756  686                  Inkay   Dark   Psychic   53      54       53
29    757  687                Malamar   Dark   Psychic   86      92       88
30    793  717                Yveltal   Dark    Flying  126     131       95

    Sp. Atk  Sp. Def  Speed  Generation  Legendary  Total Status
0        60      130     65         999      False    527  Great
1        85       42     91           2      False    407   Good
2        35       75    115           2      False    432   Good
3        80       50     65           2      False    332   Good
4       110       80     95         999      False    502  Great
5       140       90    115         999      False    602  Great
6        30       30     35           3      False    223   Good
7        60       60     70           3      False    423   Good
8        65       65     50           3      False    383   Good
9        85      115     20           3      False    483   Good
10       75       60     75           3      False    468   Good
11      115       60    115         999      False    568  Great
12      105       52     71         999      False    509  Great
13       45       85    125         999      False    514  Great
14      135       90    125         999       True    604  Great
15       50       37     66           5      False    286   Good
16       88       50    106           5      False    451   Good
17       35       70     48           5      False    353   Good
18       45      115     58           5      False    493   Good
19       80       40     65           5      False    335   Good
20      120       60    105         999      False    515  Great
21       40       40     60           5      False    345   Good
22       60       70     70           5      False    495   Good
23       45       65     60           5      False    375   Good
24       55       95     80         999      False    515  Great
25       45       50     38           5      False    305   Good
26       65       70     58           5      False    425   Good
27      125       90     98         999      False    605  Great
28       37       46     45           6      False    294   Good
29       68       75     73           6      False    488   Good
30      131       98     99         999       True    686  Great
Dragon
    index    #                     Name  Type 1    Type 2   HP  Attack  \
0     159  147                  Dratini  Dragon       NaN   41      64
1     160  148                Dragonair  Dragon       NaN   61      84
2     161  149                Dragonite  Dragon    Flying   91     134
3     365  334                  Altaria  Dragon    Flying   75      70
4     366  334      AltariaMega Altaria  Dragon     Fairy   75     110
5     406  371                    Bagon  Dragon       NaN   45      75
6     407  372                  Shelgon  Dragon       NaN   65      95
7     408  373                Salamence  Dragon    Flying   95     135
8     409  373  SalamenceMega Salamence  Dragon    Flying   95     145
9     417  380                   Latias  Dragon   Psychic   80      80
10    418  380        LatiasMega Latias  Dragon   Psychic   80     100
11    419  381                   Latios  Dragon   Psychic   80      90
12    420  381        LatiosMega Latios  Dragon   Psychic   80     130
13    425  384                 Rayquaza  Dragon    Flying  105     150
14    426  384    RayquazaMega Rayquaza  Dragon    Flying  105     180
15    491  443                    Gible  Dragon    Ground   58      70
16    492  444                   Gabite  Dragon    Ground   68      90
17    493  445                 Garchomp  Dragon    Ground  108     130
18    494  445    GarchompMega Garchomp  Dragon    Ground  108     170
19    671  610                     Axew  Dragon       NaN   46      87
20    672  611                  Fraxure  Dragon       NaN   66     117
21    673  612                  Haxorus  Dragon       NaN   76     147
22    682  621                Druddigon  Dragon       NaN   77     120
23    706  643                 Reshiram  Dragon      Fire  100     120
24    707  644                   Zekrom  Dragon  Electric  100     150
25    710  646                   Kyurem  Dragon       Ice  125     130
26    711  646       KyuremBlack Kyurem  Dragon       Ice  125     170
27    712  646       KyuremWhite Kyurem  Dragon       Ice  125     120
28    774  704                    Goomy  Dragon       NaN   45      50
29    775  705                  Sliggoo  Dragon       NaN   68      75
30    776  706                   Goodra  Dragon       NaN   90     100
31    794  718         Zygarde50% Forme  Dragon    Ground  108     100

    Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary  Total Status
0        45       50       50     50           1      False    301   Good
1        65       70       70     70           1      False    421   Good
2        95      100      100     80         999      False    601  Great
3        90       70      105     80           3      False    493   Good
4       110      110      105     80         999      False    593  Great
5        60       40       30     50           3      False    303   Good
6       100       60       50     50           3      False    423   Good
7        80      110       80    100         999      False    603  Great
8       130      120       90    120         999      False    703  Great
9        90      110      130    110         999       True    603  Great
10      120      140      150    110         999       True    703  Great
11       80      130      110    110         999       True    603  Great
12      100      160      120    110         999       True    703  Great
13       90      150       90     95         999       True    683  Great
14      100      180      100    115         999       True    783  Great
15       45       40       45     42           4      False    304   Good
16       65       50       55     82           4      False    414   Good
17       95       80       85    102         999      False    604  Great
18      115      120       95     92         999      False    704  Great
19       60       30       40     57           5      False    325   Good
20       70       40       50     67           5      False    415   Good
21       90       60       70     97         999      False    545  Great
22       90       60       90     48           5      False    490   Good
23      100      150      120     90         999       True    685  Great
24      120      120      100     90         999       True    685  Great
25       90      130       90     95         999       True    665  Great
26      100      120       90     95         999       True    705  Great
27       90      170      100     95         999       True    705  Great
28       35       55       75     40           6      False    306   Good
29       53       83      113     60           6      False    458   Good
30       70      110      150     80         999      False    606  Great
31      121       81       95     95         999       True    606  Great
Electric
    index    #                      Name    Type 1  Type 2  HP  Attack  \
0      30   25                   Pikachu  Electric     NaN  35      55
1      31   26                    Raichu  Electric     NaN  60      90
2      88   81                 Magnemite  Electric   Steel  25      35
3      89   82                  Magneton  Electric   Steel  50      60
4     108  100                   Voltorb  Electric     NaN  40      30
5     109  101                 Electrode  Electric     NaN  60      50
6     134  125                Electabuzz  Electric     NaN  65      83
7     146  135                   Jolteon  Electric     NaN  65      65
8     157  145                    Zapdos  Electric  Flying  90      90
9     186  172                     Pichu  Electric     NaN  20      40
10    193  179                    Mareep  Electric     NaN  55      40
11    194  180                   Flaaffy  Electric     NaN  70      55
12    195  181                  Ampharos  Electric     NaN  90      75
13    196  181     AmpharosMega Ampharos  Electric  Dragon  90      95
14    258  239                    Elekid  Electric     NaN  45      63
15    262  243                    Raikou  Electric     NaN  90      85
16    337  309                 Electrike  Electric     NaN  40      45
17    338  310                 Manectric  Electric     NaN  70      75
18    339  310   ManectricMega Manectric  Electric     NaN  70      75
19    340  311                    Plusle  Electric     NaN  60      50
20    341  312                     Minun  Electric     NaN  60      40
21    448  403                     Shinx  Electric     NaN  45      65
22    449  404                     Luxio  Electric     NaN  60      85
23    450  405                    Luxray  Electric     NaN  80     120
24    464  417                 Pachirisu  Electric     NaN  60      45
25    513  462                 Magnezone  Electric   Steel  70      70
26    517  466                Electivire  Electric     NaN  75     123
27    531  479                     Rotom  Electric   Ghost  50      50
28    532  479           RotomHeat Rotom  Electric    Fire  50      65
29    533  479           RotomWash Rotom  Electric   Water  50      65
30    534  479          RotomFrost Rotom  Electric     Ice  50      65
31    535  479            RotomFan Rotom  Electric  Flying  50      65
32    536  479            RotomMow Rotom  Electric   Grass  50      65
33    581  522                   Blitzle  Electric     NaN  45      60
34    582  523                 Zebstrika  Electric     NaN  75     100
35    648  587                    Emolga  Electric  Flying  55      75
36    663  602                    Tynamo  Electric     NaN  35      55
37    664  603                 Eelektrik  Electric     NaN  65      85
38    665  604                Eelektross  Electric     NaN  85     115
39    704  642  ThundurusIncarnate Forme  Electric  Flying  79     115
40    705  642    ThundurusTherian Forme  Electric  Flying  79     105
41    764  694                Helioptile  Electric  Normal  44      38
42    765  695                 Heliolisk  Electric  Normal  62      55
43    772  702                   Dedenne  Electric   Fairy  67      58

    Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary  Total Status
0        40       50       50     90           1      False    321   Good
1        55       90       80    110           1      False    486   Good
2        70       95       55     45           1      False    326   Good
3        95      120       70     70           1      False    466   Good
4        50       55       55    100           1      False    331   Good
5        70       80       80    140           1      False    481   Good
6        57       95       85    105           1      False    491   Good
7        60      110       95    130         999      False    526  Great
8        85      125       90    100         999       True    581  Great
9        15       35       35     60           2      False    207   Good
10       40       65       45     35           2      False    282   Good
11       55       80       60     45           2      False    367   Good
12       85      115       90     55         999      False    512  Great
13      105      165      110     45         999      False    612  Great
14       37       65       55     95           2      False    362   Good
15       75      115      100    115         999       True    582  Great
16       40       65       40     65           3      False    298   Good
17       60      105       60    105           3      False    478   Good
18       80      135       80    135         999      False    578  Great
19       40       85       75     95           3      False    408   Good
20       50       75       85     95           3      False    408   Good
21       34       40       34     45           4      False    267   Good
22       49       60       49     60           4      False    367   Good
23       79       95       79     70         999      False    527  Great
24       70       45       90     95           4      False    409   Good
25      115      130       90     60         999      False    539  Great
26       67       95       85     95         999      False    544  Great
27       77       95       77     91           4      False    444   Good
28      107      105      107     86         999      False    524  Great
29      107      105      107     86         999      False    524  Great
30      107      105      107     86         999      False    524  Great
31      107      105      107     86         999      False    524  Great
32      107      105      107     86         999      False    524  Great
33       32       50       32     76           5      False    300   Good
34       63       80       63    116         999      False    502  Great
35       60       75       60    103           5      False    433   Good
36       40       45       40     60           5      False    280   Good
37       70       75       70     40           5      False    410   Good
38       80      105       80     50         999      False    520  Great
39       70      125       80    111         999       True    585  Great
40       70      145       80    101         999       True    585  Great
41       33       61       43     70           6      False    295   Good
42       52      109       94    109           6      False    487   Good
43       57       81       67    101           6      False    437   Good
Fairy
    index    #        Name Type 1  Type 2   HP  Attack  Defense  Sp. Atk  \
0      40   35    Clefairy  Fairy     NaN   70      45       48       60
1      41   36    Clefable  Fairy     NaN   95      70       73       95
2     187  173      Cleffa  Fairy     NaN   50      25       28       45
3     189  175      Togepi  Fairy     NaN   35      20       65       40
4     190  176     Togetic  Fairy  Flying   55      40       85       80
5     225  209    Snubbull  Fairy     NaN   60      80       50       40
6     226  210    Granbull  Fairy     NaN   90     120       75       60
7     519  468    Togekiss  Fairy  Flying   85      50       95      120
8     737  669     Flabébé  Fairy     NaN   44      38       39       61
9     738  670     Floette  Fairy     NaN   54      45       47       75
10    739  671     Florges  Fairy     NaN   78      65       68      112
11    752  682    Spritzee  Fairy     NaN   78      52       60       63
12    753  683  Aromatisse  Fairy     NaN  101      72       72       99
13    754  684     Swirlix  Fairy     NaN   62      48       66       59
14    755  685    Slurpuff  Fairy     NaN   82      80       86       85
15    770  700     Sylveon  Fairy     NaN   95      65       65      110
16    792  716     Xerneas  Fairy     NaN  126     131       95      131

    Sp. Def  Speed  Generation  Legendary  Total Status
0        65     35           1      False    324   Good
1        90     60           1      False    484   Good
2        55     15           2      False    220   Good
3        65     20           2      False    247   Good
4       105     40           2      False    407   Good
5        40     30           2      False    302   Good
6        60     45           2      False    452   Good
7       115     80         999      False    549  Great
8        79     42           6      False    309   Good
9        98     52           6      False    377   Good
10      154     75         999      False    558  Great
11       65     23           6      False    347   Good
12       89     29           6      False    468   Good
13       57     49           6      False    347   Good
14       75     72           6      False    486   Good
15      130     60         999      False    531  Great
16       98     99         999       True    686  Great
Fighting
    index    #                   Name    Type 1   Type 2   HP  Attack  \
0      61   56                 Mankey  Fighting      NaN   40      80

In [320]:
gg=g.get_group('Fire').head()
gg.reset_index().drop(columns = ['index','#'])
gg

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total,Status
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,310,Good
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False,406,Good
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,999,False,535,Great
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,999,False,635,Great
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,999,False,635,Great

In [ ]:
ff = read_csv()